spring:
  profiles:
    active: hrz
---
env.name: qa
---
basicUser: auto+do-not-touch-this-user@straighterline.com
commonPassword: Secretpwd@1
---
spring:
  profiles: wgu
datasource:
  name: Western Government University
  url: https://${env.name}.academy.wgu.edu
---
spring:
  profiles: csu
datasource:
  name: Colorado University
  url: https://${env.name}.csuglobalbridge.straighterline.com
---
spring:
  profiles: ftk
datasource:
  name: Fastrack
  url: https://${env.name}.brighthorizons.straighterline.net
---
spring:
  profiles: hrz
datasource:
  name: Horizont
  url: https://${env.name}.horizons.straighterline.net
---
spring:
  profiles: feature
datasource:
  name: Feature
  url: https://${env.name}.feat.brighthorizons.straighterline.net
#  env.name = en-13220