spring:
  profiles:
    active: goodreads
---
env.name: www
---
browser: chrome
---
run.from: local
---
spring:
  profiles: goodreads
datasource:
  name: Goodreads
  uri: goodreads.com
  url: https://${env.name}.${datasource.uri}
---
elementWait: 5
pageLoadWait: 120
jsScriptWait: 120